#!/bin/bash
### BEGIN INIT INFO
## Provides:          keepTunelUp
## Required-Start:    $local_fs $network
## Required-Stop:     $local_fs
## Default-Start:     2 3 4 5
## Default-Stop:      0 1 6
## Short-Description: keepTunelUp
## Description:       keepTunelUp
#### END INIT INFO

# Source function library.
#. /etc/init.d/functions

start() {
    # code to start app comes here
    sudo -u root bash /home/systemacs/Documents/keepTunelUp/ktu.sh
}

stop() {
    # code to stop app comes here
    sudo -u root tmux kill-session -t ktu
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    #status)
       # code to check status of app comes here
       # example: status program_name
       # ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0